## This is the configuration file for Headroom.
## See https://github.com/vaclavsvejcar/headroom for more details.

## Defines the behaviour how to handle license headers, possible options are:
##   - add     = (default) adds license header to files with no existing header
##   - drop    = drops existing license header from without replacement
##   - replace = adds or replaces existing license header
run-mode: add

## Allows to change behaviour of license header detection.
license-headers:
  ## Haskell configuration
  haskell:
    file-extensions: ["hs"]
    put-after: []
    starts-with: "{-"
    ends-with: "-}"

  ## HTML configuration
  html:
    file-extensions: ["htm", "html"]
    put-after: []
    starts-with: "<!--"
    ends-with: "-->"
