## This is the configuration file for Headroom.
## See https://github.com/vaclavsvejcar/headroom for more details.

## Defines the behaviour how to handle license headers, possible options are:
##   - add     = (default) adds license header to files with no existing header
##   - drop    = drops existing license header from without replacement
##   - replace = adds or replaces existing license header
run-mode: add

## Allows to change behaviour of license header detection.
license-headers:
  ## CSS configuration
  css:
    file-extensions: ["css"]
    put-after: []
    put-before: []
    starts-with: "/*"
    ends-with: "*/"

  ## Haskell configuration
  haskell:
    file-extensions: ["hs"]
    put-after: []
    put-before: []
    starts-with: "{-|"
    ends-with: "-}"

  ## HTML configuration
  html:
    file-extensions: ["htm", "html"]
    put-after: []
    put-before: []
    starts-with: "<!--"
    ends-with: "-->"

  ## Java configuration
  java:
    file-extensions: ["java"]
    put-after: []
    put-before: ["^package"]
    starts-with: "/*"
    ends-with: "*/"

  ## JS configuration
  js:
    file-extensions: ["js"]
    put-after: []
    put-before: []
    starts-with: "/*"
    ends-with: "*/"

  ## Scala configuration
  scala:
    file-extensions: ["scala"]
    put-after: []
    put-before: ["^package"]
    starts-with: "/*"
    ends-with: "*/"
