## This is the global configuration file for Headroom.
## See https://github.com/vaclavsvejcar/headroom for more details.

## Whether Headroom should automatically check for available updates. 
check-for-updates: true