## This is the configuration file for Headroom.
## See https://github.com/vaclavsvejcar/headroom for more details.

## Defines the behaviour how to handle license headers, possible options are:
##   - add     = (default) adds license header to files with no existing header
##   - drop    = drops existing license header from without replacement
##   - replace = adds or replaces existing license header
run-mode: replace

## Paths to source code files (either files or directories).
source-paths:
  - app
  - src

## Paths to template files (either files or directories).
template-paths:
  - doc/templates

## Variables (key-value) to replace in templates.
variables:
  author: Vaclav Svejcar
  license: BSD-3-Clause
  email: vaclav.svejcar@gmail.com
  year: 2019-2020

license-headers:
  haskell:
    put-after: ["^{-#"]
    put-before: ["^module"]
    margin-top-code: 1
    margin-bottom-code: 1
    margin-bottom-file: 1
