name: headroom
version: 0.2.0.0
homepage: https://github.com/vaclavsvejcar/headroom
license: BSD3
license-file: LICENSE
author: Vaclav Svejcar
maintainer: vaclav.svejcar@gmail.com
copyright: Copyright (c) 2019-2020 Vaclav Svejcar
github: vaclavsvejcar/headroom
category: Utils
synopsis: License Header Manager
description: >
  So you are tired of managing license headers in your codebase by hand? Then
  Headroom is the right tool for you! Now you can define your license header as
  Mustache template, put all the variables (such as author's name, year, etc.)
  into the YAML config file and Headroom will take care to add such license
  headers to all your source code files.

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md
  - embedded/**
  - embedded/license/*/*.mustache
  - test-data/*
  - test-data/code-samples/*/*
  - test-data/configs/*
  - test-data/test-traverse/*
  - test-data/test-traverse/foo/*
  - test-data/test-traverse/foo/bar/*

dependencies:
  - base >= 4.7 && < 5
  - optparse-applicative
  - rio

ghc-options:
  - -optP-Wno-nonportable-include-path
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Werror=incomplete-patterns

executables:
  headroom:
    main: Main.hs
    source-dirs: app
    dependencies:
      - headroom
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

library:
  source-dirs: src
  dependencies:
    - aeson
    - either
    - file-embed
    - lens
    - mustache
    - pcre-heavy
    - pcre-light
    - template-haskell
    - text
    - time
    - validation
    - yaml

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - aeson
      - headroom
      - hspec
      - QuickCheck
  doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - doctest
